<a href="https://colab.research.google.com/github/isadoraxaavier/trabalho_estatistica/blob/Gabriel/Estat%C3%ADstica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')

# caminho do arquivo dentro do seu Drive
path = "/content/drive/MyDrive/Netflix (2).xlsx"
df = pd.read_excel(path)
df.head()

Mounted at /content/drive

,show_id,type,title,director,cast,country,date_added,release_year,rating,Classificação equivalente no Brasil,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020.0,PG-13,12 anos,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,18 anos,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,18 anos,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,18 anos,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,18 anos,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
# 🔎 Diagnóstico inicial da base Netflix
print("📌 Informações gerais:\n")
print("Formato (linhas, colunas):", df.shape)
print("\nNomes das colunas:\n", df.columns.tolist())

print("\n🔍 Tipos de dados e nulos:\n")
print(df.info())

print("\n🔍 Quantidade de valores nulos por coluna:\n")
print(df.isna().sum())

print("\n📌 Primeiras linhas da base:\n")
display(df.head())

📌 Informações gerais:

Formato (linhas, colunas): (8808, 13)

Nomes das colunas:
 ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'Classificação equivalente no Brasil', 'duration', 'listed_in', 'description']

🔍 Tipos de dados e nulos:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8808 entries, 0 to 8807
Data columns (total 13 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   show_id                              8807 non-null   object
 1   type                                 8807 non-null   object
 2   title                                8790 non-null   object
 3   director                             6173 non-null   object
 4   cast                                 7982 non-null   object
 5   country                              7976 non-null   object
 6   date_added                           8797 non-null   object
 7   release_year                         8807 non-null   float64
 8   rating                               8800 non-null   object
 9   Classificação equivalente no Brasil  8800 non-null   object
 10  duration                             8537 non-null   object
 11  listed_in                            8807 non-null   object
 12  description                          8807 non-null   object
dtypes: float64(1), object(12)
memory usage: 894.7+ KB
None

🔍 Quantidade de valores nulos por coluna:

show_id                                   1
type                                      1
title                                    18
director                               2635
cast                                    826
country                                 832
date_added                               11
release_year                              1
rating                                    8
Classificação equivalente no Brasil       8
duration                                271
listed_in                                 1
description                               1
dtype: int64

📌 Primeiras linhas da base:

,show_id,type,title,director,cast,country,date_added,release_year,rating,Classificação equivalente no Brasil,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020.0,PG-13,12 anos,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,18 anos,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,18 anos,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,18 anos,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,18 anos,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [8]:
# Limpeza e criação da coluna de Década
df = df.dropna(subset=["type", "rating", "country", "release_year"])
df["Década"] = (df["release_year"] // 10 * 10).astype(int).astype(str) + "–" + ((df["release_year"] // 10 * 10 + 9).astype(int)).astype(str)

# === 3A - Tabela de Dupla Entrada: Tipo x Classificação ===
print("\n=== 3A - Tipo x Classificação (Rating) ===")
tabela_tipo_classificacao = pd.crosstab(df["type"], df["rating"], margins=True, margins_name="Total")
display(tabela_tipo_classificacao)

=== 3A - Tipo x Classificação (Rating) ===

rating,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR,Total
type,,,,,,,,,,,,,,,
Movie,41,3,75,281,482,787,1307,109,1924,503,84,83,4,3,5686
TV Show,0,0,5,0,0,1,623,81,1007,269,143,153,1,0,2283
Total,41,3,80,281,482,788,1930,190,2931,772,227,236,5,3,7969

In [10]:
# === 3B - Tabela de Dupla Entrada: País x Tipo ===
print("\n=== 3B - País x Tipo ===")
tabela_pais_tipo = pd.crosstab(df["country"], df["type"], margins=True, margins_name="Total")
display(tabela_pais_tipo.head(20))  # Mostra os 20 primeiros países

=== 3B - País x Tipo ===

type                                                Movie  TV Show  Total
country
Argentina                                              38       18     56
Argentina, Brazil, France, Poland, Germany, Den...      1        0      1
Argentina, Chile                                        2        0      2
Argentina, Chile, Peru                                  1        0      1
Argentina, France                                       1        0      1
Argentina, France, United States, Germany, Qatar        1        0      1
Argentina, Italy                                        1        0      1
Argentina, Spain                                        7        1      8
Argentina, United States                                1        0      1
Argentina, United States, Mexico                        0        1      1
Argentina, Uruguay, Serbia                              1        0      1
Argentina, Uruguay, Spain, France                       1        0      1
Argentina, Venezuela                                    1        0      1
Australia                                              39       47     86
Australia, Armenia, Japan, Jordan, Mexico, Mong...      1        0      1
Australia, Canada                                       1        1      2
Australia, France                                       1        0      1
Australia, France, Ireland                              1        0      1
Australia, Germany                                      0        1      1
Australia, India                                        1        0      1

In [12]:
# === 3C - Tabela de Dupla Entrada: Tipo x Década ===
print("\n=== 3C - Tipo x Década ===")
tabela_tipo_decada = pd.crosstab(df["type"], df["Década"], margins=True, margins_name="Total")
display(tabela_tipo_decada)

=== 3C - Tipo x Década ===

Década,1940–1949,1950–1959,1960–1969,1970–1979,1980–1989,1990–1999,2000–2009,2010–2019,2020–2029,Total
type,,,,,,,,,,
Movie,12,11,22,66,114,231,664,3936,630,5686
TV Show,2,0,2,4,7,30,122,1511,605,2283
Total,14,11,24,70,121,261,786,5447,1235,7969